# Generated by Django 4.1.7 on 2023-03-02 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_remove_customer_store_custo_first_n_8f83e0_idx_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='customer',
            new_name='store_custo_last_na_e6a359_idx',
            old_name='store_custo_last_na_2e448d_idx',
        ),
        migrations.AlterModelTable(
            name='customer',
            table='store_customers',
        ),
    ]
